# Generated by Django 4.2.13 on 2024-06-26 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac_app', '0002_remove_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default=12345678901, max_length=11, unique=True, verbose_name='手机号'),
            preserve_default=False,
        ),
    ]
